when:
  event: tag
  branch: main

steps:
  notify-start:
    image: appleboy/drone-discord
    settings:
      webhook_id:
        from_secret: DISCORD_WEBHOOK_ID
      webhook_token:
        from_secret: DISCORD_WEBHOOK_TOKEN
      message: "🚀 `[ clx-etl : ${CI_COMMIT_TAG} ]` Production Deploy Start"

  build-production:
    image: woodpeckerci/plugin-kaniko
    settings:
      registry: 10.10.10.112:5000
      repo: coinluxer/clx-etl
      tags:
        - ${CI_COMMIT_TAG}
      skip_tls_verify: true
      cache: true

  deploy-production:
    depends_on:
      - build-production
    image: prefecthq/prefect:3.6.4-python3.13
    environment:
      PREFECT_API_URL: http://10.10.10.101:4200/api
      ENV: production

      REGISTRY: 10.10.10.112:5000
      IMAGE_NAME: coinluxer/clx-etl
      VERSION: ${CI_COMMIT_TAG}
      
    commands:
      - uv sync --frozen --no-dev
      - .venv/bin/python src/deploy.py

  notify-success:
    when:
      status: success
    depends_on:
      - deploy-production
    image: appleboy/drone-discord
    settings:
      webhook_id:
        from_secret: DISCORD_WEBHOOK_ID
      webhook_token:
        from_secret: DISCORD_WEBHOOK_TOKEN
      message: "✅ `[ clx-etl : ${CI_COMMIT_TAG} ]` PROD Deploy Success"

  notify-failure:
    when:
      status: failure
    depends_on:
      - deploy-production
    image: appleboy/drone-discord
    settings:
      webhook_id:
        from_secret: DISCORD_WEBHOOK_ID
      webhook_token:
        from_secret: DISCORD_WEBHOOK_TOKEN
      message: "❌ `[ clx-etl : ${CI_COMMIT_TAG} ]` PROD Deploy Failed"
