when:
  event: push
  branch: main

steps:
  build-staging:
    image: woodpeckerci/plugin-kaniko
    settings:
      registry: 10.10.10.112:5000
      repo: coinluxer/clx-etl
      tags:
        - ${CI_COMMIT_SHA:0:8}
      skip_tls_verify: true
      cache: true

  deploy-staging:
    depends_on:
      - build-staging
    image: prefecthq/prefect:3.6.4-python3.13
    environment:
      PREFECT_API_URL: http://10.10.10.101:4200/api
      ENV: staging
      IMAGE_URL: 10.10.10.112:5000/coinluxer/clx-etl:${CI_COMMIT_SHA:0:8}

    commands:
      - python src/deploy.py

  notify-success:
    when:
      status: success
    depends_on:
      - deploy-staging
    image: appleboy/drone-discord
    settings:
      webhook_id:
        from_secret: DISCORD_WEBHOOK_ID
      webhook_token:
        from_secret: DISCORD_WEBHOOK_TOKEN
      message: "✅ `[ clx-etl : ${CI_COMMIT_SHA:0:8} ]` Staging Deploy Success"

  notify-failure:
    when:
      status: failure
    depends_on:
      - deploy-staging
    image: appleboy/drone-discord
    settings:
      webhook_id:
        from_secret: DISCORD_WEBHOOK_ID
      webhook_token:
        from_secret: DISCORD_WEBHOOK_TOKEN
      message: "❌ `[ clx-etl : ${CI_COMMIT_SHA:0:8} ]` Staging Deploy Failed"
