when:
  event: push
  branch: main

steps:
  build-staging:
    image: woodpeckerci/plugin-kaniko
    settings:
      registry: 10.10.10.112:5000
      repo: coinluxer/clx-etl
      tags:
        - ${CI_COMMIT_SHA:0:8}
      skip_tls_verify: true
      cache: true

  deploy-staging:
    depends_on:
      - build-staging
    image: alpine
    environment:
      HOST: 10.10.10.137
      REGISTRY: 10.10.10.112:5000
      IMAGE_NAME: coinluxer/clx-etl

      SSH_PRIVATE_KEY:
        from_secret: SSH_PRIVATE_KEY
      SSH_KNOWN_HOSTS:
        from_secret: SSH_KNOWN_HOSTS
      DORIS_PASSWORD:
        from_secret: DORIS_PASSWORD_STG
      MYSQL_PASSWORD:
        from_secret: MYSQL_PASSWORD_STG

    commands:
      - apk add openssh-client docker-cli
      - mkdir -p ~/.ssh
      - printf "%s" "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
      - chmod 600 ~/.ssh/id_rsa
      - printf "%s" "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts

      - |
          ssh -o StrictHostKeyChecking=yes hhe@$HOST "
            set -xe;

            docker pull $REGISTRY/$IMAGE_NAME:${CI_COMMIT_SHA:0:8};

            docker stop clx-etl || true;
            docker rm clx-etl || true;

            docker run -d \
              --name clx-etl \
              --restart always \
              -e ENV=staging \
              -e DORIS_HOST=192.168.50.136 \
              -e DORIS_HTTP_PORT=8030 \
              -e DORIS_PORT=9030 \
              -e DORIS_USER=etl \
              -e DORIS_PASSWORD=$DORIS_PASSWORD \
              -e DORIS_DB=clx_prod \
              -e MYSQL_HOST=192.168.50.137 \
              -e MYSQL_PORT=3306 \
              -e MYSQL_USER=etl \
              -e MYSQL_PASSWORD=$MYSQL_PASSWORD \
              -e MYSQL_DB=clx_prod \
              $REGISTRY/$IMAGE_NAME:${CI_COMMIT_SHA:0:8};

            echo 'Waiting 15 seconds...';
            sleep 15;

            STATUS=\$(docker inspect -f '{{.State.Status}}' clx-etl)
            RESTARTS=\$(docker inspect -f '{{.RestartCount}}' clx-etl)

            if [ \"\$STATUS\" != \"running\" ]; then
              echo '❌ STG container is NOT running:' \$STATUS
              docker logs clx-etl
              exit 1
            fi

            if [ \$RESTARTS -gt 0 ]; then
              echo '❌ STG container restarted' \$RESTARTS 'times.'
              docker logs clx-etl
              exit 1
            fi

            echo 'STG OK 🚀';
          "

  notify-success:
    when:
      status: success
    depends_on:
      - deploy-staging
    image: appleboy/drone-discord
    settings:
      webhook_id:
        from_secret: DISCORD_WEBHOOK_ID
      webhook_token:
        from_secret: DISCORD_WEBHOOK_TOKEN
      message: "✅ [`clx-etl` : `${CI_COMMIT_SHA:0:8}`] Staging Deploy Success"

  notify-failure:
    when:
      status: failure
    depends_on:
      - deploy-staging
    image: appleboy/drone-discord
    settings:
      webhook_id:
        from_secret: DISCORD_WEBHOOK_ID
      webhook_token:
        from_secret: DISCORD_WEBHOOK_TOKEN
      message: "❌ [`clx-etl` : `${CI_COMMIT_SHA:0:8}`] Staging Deploy Failed"
